# Generated by Django 5.2.3 on 2025-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=10, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
